const tintColor = '#2f95dc';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  headerBackgroundColor: '#343a40',
  headerMenuBackgroundColor: '#292d32',
  headerMenuBorder: '#414850',
  menuSideSeparator: '#eff0f2',
  noticeText: '#fff',
  white: '#fff',
  choosenGreen: '#179b6f',
  choosenBackground: 'rgba(23,155,111,0.1)',
  muted: '#fb6566',
  black: '#000',
  bubbleBack: '#fef4af',
  bubbleText: '#958b5c',
  messageBackGround: '#179b6f',
};
